export const ONE_HOUR_IN_SECONDS = 60 * 60
export const ONE_DAY_IN_SECONDS = ONE_HOUR_IN_SECONDS * 24
export const TWO_WEEKS_IN_SECONDS = ONE_DAY_IN_SECONDS * 14
export const THIRTY_DAYS_IN_SECONDS = ONE_DAY_IN_SECONDS * 30
export const SIXTY_DAYS_IN_SECONDS = ONE_DAY_IN_SECONDS * 60
export const ONE_YEAR_IN_SECONDS = ONE_DAY_IN_SECONDS * 365
export const SIXTEEN_YEARS_IN_SECONDS = ONE_YEAR_IN_SECONDS * 16
