export const amenitiesData = () => ({
  Accessories: [
    'Awning',
    'Campingchairsprovided',
    'Inverter',
    'LinensProvided',
    'LevelingJacks',
    'Generator',
    'Solar',
    'TowHitch',
  ],
  Bathroom: ['InsideShower', 'OutsideShower', 'Toilet'],
  Temperature: ['AirConditioner', 'Heater'],
  Electronics: [
    'AuxInput',
    'BackupCamera',
    'CdPlayer',
    'GPSUnitAvailable',
    'Satellite',
    'Radio',
    'TV_DVD',
    'USBInput',
    'WiFi',
  ],
  Kitchen: ['Refrigerator', 'Stove_Range', 'Microwave', 'KitchenSink', 'DiningTable', 'Freezer', 'Oven'],
  Other: [
    'Family_kidfriendly',
    'Petfriendly',
    'HandicapAccessible',
    'Vintage',
    'FullWinterRentalAvailable',
    'ExtraStorage',
    'Parking',
  ],
})
