/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = {
  [path: `/Campground/${string}`]: {
    get: {
      parameters: {
        query?: {
          languageCode?: "XX" | "En" | "Fr";
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.CampgroundResponse"];
          };
        };
      };
    };
  };
  [path: `/Campground/${string}`]: {
    get: {
      parameters: {
        query?: {
          languageCode?: "XX" | "En" | "Fr";
        };
        path: {
          route: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.CampgroundResponse"];
          };
        };
      };
    };
  };
  [path: `/Campground/Photos/${string}`]: {
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PagedResponse[String]"];
          };
        };
      };
    };
  };
  "/Campground/Search": {
    get: {
      parameters: {
        query?: {
          CampgroundId?: string;
          Brand?: string;
          BrandId?: string;
          Latitude?: number;
          Longitude?: number;
          NeLat?: number;
          NeLng?: number;
          SwLat?: number;
          SwLng?: number;
          DistanceKm?: number;
          Region?: "XX" | "AL" | "AK" | "AZ" | "AR" | "CA" | "CO" | "CT" | "DE" | "DC" | "FL" | "GA" | "HI" | "ID" | "IL" | "IN" | "IA" | "KS" | "KY" | "LA" | "ME" | "MD" | "MA" | "MI" | "MN" | "MS" | "MO" | "MT" | "NE" | "NV" | "NH" | "NJ" | "NM" | "NY" | "NC" | "ND" | "OH" | "OK" | "OR" | "PA" | "RI" | "SC" | "SD" | "TN" | "TX" | "UT" | "VT" | "VA" | "WA" | "WV" | "WI" | "WY" | "AB" | "BC" | "MB" | "NB" | "NL" | "NT" | "NS" | "NU" | "ON" | "PE" | "QC" | "SK" | "YT";
          Country?: "XX" | "CA" | "US";
          Page?: number;
          PageSize?: number;
          LanguageCode?: "XX" | "En" | "Fr";
          SortBy?: "Default" | "DistanceAsc" | "DatePublishedDesc";
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PagedResponse[Rvezy.Campgrounds.Api.Dtos.Response.CampgroundResponse]"];
          };
        };
      };
    };
  };
  "/HealthCheck": {
    get: operations["HealthCheck"];
  };
  [path: `/Place/${string}`]: {
    get: {
      parameters: {
        query?: {
          languageCode?: "XX" | "En" | "Fr";
        };
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PlaceResponse"];
          };
        };
      };
    };
  };
  [path: `/Place/${string}`]: {
    get: {
      parameters: {
        query?: {
          languageCode?: "XX" | "En" | "Fr";
        };
        path: {
          route: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PlaceResponse"];
          };
        };
      };
    };
  };
  [path: `/Place/Faq/${string}`]: {
    get: {
      parameters: {
        query?: {
          languageCode?: "XX" | "En" | "Fr";
        };
        path: {
          placeId: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PagedResponse[Rvezy.Campgrounds.Api.Dtos.Response.PlaceFaqResponse]"];
          };
        };
      };
    };
  };
  [path: `/Place/Faq/${string}`]: {
    get: {
      parameters: {
        query?: {
          languageCode?: "XX" | "En" | "Fr";
        };
        path: {
          route: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PagedResponse[Rvezy.Campgrounds.Api.Dtos.Response.PlaceFaqResponse]"];
          };
        };
      };
    };
  };
  "/Place/Search": {
    get: {
      parameters: {
        query?: {
          PlaceId?: string;
          Latitude?: number;
          Longitude?: number;
          DistanceKm?: number;
          PlaceType?: "World" | "Country" | "Region" | "City";
          Region?: "XX" | "AL" | "AK" | "AZ" | "AR" | "CA" | "CO" | "CT" | "DE" | "DC" | "FL" | "GA" | "HI" | "ID" | "IL" | "IN" | "IA" | "KS" | "KY" | "LA" | "ME" | "MD" | "MA" | "MI" | "MN" | "MS" | "MO" | "MT" | "NE" | "NV" | "NH" | "NJ" | "NM" | "NY" | "NC" | "ND" | "OH" | "OK" | "OR" | "PA" | "RI" | "SC" | "SD" | "TN" | "TX" | "UT" | "VT" | "VA" | "WA" | "WV" | "WI" | "WY" | "AB" | "BC" | "MB" | "NB" | "NL" | "NT" | "NS" | "NU" | "ON" | "PE" | "QC" | "SK" | "YT";
          Country?: "XX" | "CA" | "US";
          Page?: number;
          PageSize?: number;
          LanguageCode?: "XX" | "En" | "Fr";
          SortBy?: "Default" | "DistanceAsc";
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PagedResponse[Rvezy.Campgrounds.Api.Dtos.Response.PlaceResponse]"];
          };
        };
      };
    };
  };
};

export type webhooks = Record<string, never>;

export type components = {
  schemas: {
    "Rvezy.Campgrounds.Api.Dtos.Response.CampgroundAmenitiesResponse": {
      has15AmpHookup?: boolean | null;
      has20AmpHookup?: boolean | null;
      has30AmpHookup?: boolean | null;
      has50AmpHookup?: boolean | null;
      hasBeach?: boolean | null;
      hasBoatLaunch?: boolean | null;
      hasCableTV?: boolean | null;
      hasDumpStation?: boolean | null;
      hasEletricalHookup?: boolean | null;
      hasFirewood?: boolean | null;
      hasFishing?: boolean | null;
      hasGeneralStore?: boolean | null;
      hasGrills?: boolean | null;
      hasHiking?: boolean | null;
      hasInternet?: boolean | null;
      hasLaundryFacilities?: boolean | null;
      hasPlayground?: boolean | null;
      hasPool?: boolean | null;
      hasPropane?: boolean | null;
      hasPullThrusSitesAvailable?: boolean | null;
      hasRVStorage?: boolean | null;
      hasSewerHookup?: boolean | null;
      hasShowers?: boolean | null;
      hasTables?: boolean | null;
      hasTentsSites?: boolean | null;
      hasToilets?: boolean | null;
      hasTrails?: boolean | null;
      hasWaterHookup?: boolean | null;
      isBigRigFriendly?: boolean | null;
      isMotorizedOnly?: boolean | null;
      isPetFriendly?: boolean | null;
    };
    "Rvezy.Campgrounds.Api.Dtos.Response.CampgroundResponse": {
      amenities?: components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.CampgroundAmenitiesResponse"];
      ancestry?: components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PlaceAncestorResponse"][] | null;
      bookingLink?: string | null;
      /** @enum {string|null} */
      bookingProvider?: "Direct" | "Spot2Nite" | null;
      bookingSeasonEnds?: string | null;
      bookingSeasonStarts?: string | null;
      brand?: string | null;
      city?: string | null;
      country?: string | null;
      /** @enum {string|null} */
      countryCode?: "XX" | "CA" | "US" | null;
      /** Format: double */
      distance?: number | null;
      emailAddress?: string | null;
      fullAddress?: string | null;
      fullCompactAddress?: string | null;
      /** Format: uuid */
      id?: string;
      /** Format: double */
      latitude?: number;
      /** Format: double */
      longitude?: number;
      /** Format: int32 */
      maxRVLength?: number | null;
      name?: string | null;
      /** @enum {string|null} */
      nightlyRates?: "Free" | "Lowest" | "Low" | "Medium" | "High" | "Highest" | null;
      /** Format: int32 */
      numberOfSites?: number | null;
      phoneNumber?: string | null;
      photos?: string[] | null;
      /** Format: uuid */
      placeId?: string;
      placeName?: string | null;
      postalCode?: string | null;
      region?: string | null;
      /** @enum {string|null} */
      regionCode?: "XX" | "AL" | "AK" | "AZ" | "AR" | "CA" | "CO" | "CT" | "DE" | "DC" | "FL" | "GA" | "HI" | "ID" | "IL" | "IN" | "IA" | "KS" | "KY" | "LA" | "ME" | "MD" | "MA" | "MI" | "MN" | "MS" | "MO" | "MT" | "NE" | "NV" | "NH" | "NJ" | "NM" | "NY" | "NC" | "ND" | "OH" | "OK" | "OR" | "PA" | "RI" | "SC" | "SD" | "TN" | "TX" | "UT" | "VT" | "VA" | "WA" | "WV" | "WI" | "WY" | "AB" | "BC" | "MB" | "NB" | "NL" | "NT" | "NS" | "NU" | "ON" | "PE" | "QC" | "SK" | "YT" | null;
      slug?: string | null;
      streetAddress?: string | null;
      websiteLink?: string | null;
    };
    "Rvezy.Campgrounds.Api.Dtos.Response.PagedResponse[Rvezy.Campgrounds.Api.Dtos.Response.CampgroundResponse]": {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageCount?: number;
      /** Format: int32 */
      pageSize?: number;
      results?: components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.CampgroundResponse"][] | null;
      /** Format: int32 */
      totalResults?: number;
    };
    "Rvezy.Campgrounds.Api.Dtos.Response.PagedResponse[Rvezy.Campgrounds.Api.Dtos.Response.PlaceFaqResponse]": {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageCount?: number;
      /** Format: int32 */
      pageSize?: number;
      results?: components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PlaceFaqResponse"][] | null;
      /** Format: int32 */
      totalResults?: number;
    };
    "Rvezy.Campgrounds.Api.Dtos.Response.PagedResponse[Rvezy.Campgrounds.Api.Dtos.Response.PlaceResponse]": {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageCount?: number;
      /** Format: int32 */
      pageSize?: number;
      results?: components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PlaceResponse"][] | null;
      /** Format: int32 */
      totalResults?: number;
    };
    "Rvezy.Campgrounds.Api.Dtos.Response.PagedResponse[String]": {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageCount?: number;
      /** Format: int32 */
      pageSize?: number;
      results?: string[] | null;
      /** Format: int32 */
      totalResults?: number;
    };
    "Rvezy.Campgrounds.Api.Dtos.Response.PlaceAncestorResponse": {
      code?: string | null;
      /** Format: uuid */
      id?: string;
      name?: string | null;
      /** @enum {string} */
      placeType?: "World" | "Country" | "Region" | "City";
      route?: string | null;
    };
    "Rvezy.Campgrounds.Api.Dtos.Response.PlaceFaqResponse": {
      answer?: string | null;
      /** Format: uuid */
      id?: string;
      question?: string | null;
    };
    "Rvezy.Campgrounds.Api.Dtos.Response.PlaceResponse": {
      ancestry?: components["schemas"]["Rvezy.Campgrounds.Api.Dtos.Response.PlaceAncestorResponse"][] | null;
      city?: string | null;
      code?: string | null;
      country?: string | null;
      /** @enum {string|null} */
      countryCode?: "XX" | "CA" | "US" | null;
      /** Format: double */
      distance?: number | null;
      /** Format: uuid */
      id?: string;
      /** Format: double */
      latitude?: number;
      /** Format: double */
      latitudeNorth?: number | null;
      /** Format: double */
      latitudeSouth?: number | null;
      /** Format: double */
      longitude?: number;
      /** Format: double */
      longitudeEast?: number | null;
      /** Format: double */
      longitudeWest?: number | null;
      name?: string | null;
      placeName?: string | null;
      /** @enum {string} */
      placeType?: "World" | "Country" | "Region" | "City";
      region?: string | null;
      /** @enum {string|null} */
      regionCode?: "XX" | "AL" | "AK" | "AZ" | "AR" | "CA" | "CO" | "CT" | "DE" | "DC" | "FL" | "GA" | "HI" | "ID" | "IL" | "IN" | "IA" | "KS" | "KY" | "LA" | "ME" | "MD" | "MA" | "MI" | "MN" | "MS" | "MO" | "MT" | "NE" | "NV" | "NH" | "NJ" | "NM" | "NY" | "NC" | "ND" | "OH" | "OK" | "OR" | "PA" | "RI" | "SC" | "SD" | "TN" | "TX" | "UT" | "VT" | "VA" | "WA" | "WV" | "WI" | "WY" | "AB" | "BC" | "MB" | "NB" | "NL" | "NT" | "NS" | "NU" | "ON" | "PE" | "QC" | "SK" | "YT" | null;
      route?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = {

  HealthCheck: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "text/plain": string;
        };
      };
    };
  };
};
