/**
 * This file is automatically generated. DO NOT MODIFY
 *
 * Generated By: scripts/generatePointOfInterestComponentConfig.js
 * Timestamp: Mon Jul 10 2023 13:00:39 GMT-0300 (Brasilia Standard Time)
 */

export default {
  Campground: {
    CanonicalSlugs: { en: 'campground', fr: 'camping' },
    Component: 'Campground',
    ComponentType: 'PointOfInterest',
    Id: '7cd1d195-422e-4f21-96a2-1dabe8babc50',
    Indexable: true,
    Name: 'Campground',
    Slugs: ['campground', 'camping'],
  },
  Campgrounds: {
    CanonicalSlugs: { en: 'campgrounds', fr: 'campings' },
    Component: 'Campgrounds',
    ComponentType: 'Action',
    Id: '0ad647d9-b306-4724-a649-f6c3e3a14de9',
    Indexable: true,
    Name: 'Campgrounds',
    Slugs: ['campgrounds', 'campings'],
  },
  City: {
    Component: 'City',
    ComponentType: 'PointOfInterest',
    Id: '395c30db-44bf-41a1-a1fe-d764d8fffaa0',
    Indexable: true,
    Name: 'City',
  },
  Country: {
    Component: 'Country',
    ComponentType: 'PointOfInterest',
    Id: '180fa908-d989-4923-9801-58106250d2cd',
    Indexable: true,
    Name: 'Country',
  },
  Destinations: {
    Component: 'Destinations',
    ComponentType: 'Action',
    Id: '65b71e51-52ad-472e-8a89-2cf547cbefbb',
    Indexable: true,
    Name: 'Destinations',
  },
  Park: {
    CanonicalSlugs: { en: 'park', fr: 'parc' },
    Component: 'Park',
    ComponentType: 'PointOfInterest',
    Id: '54d0daa7-9bce-40d4-99ac-4ed78bf4a896',
    Indexable: true,
    Name: 'Park',
    Slugs: ['park', 'parc'],
  },
  RVRentals: {
    CanonicalSlugs: { en: 'rv-rentals', fr: 'location-vr' },
    Component: 'RVRentals',
    ComponentType: 'Action',
    Id: '6afe3282-21b4-4c2d-8481-d95524ce59c6',
    Indexable: true,
    Name: 'RVRentals',
    Slugs: ['rv-rentals', 'rv-rental', 'location-vr'],
  },
  Region: {
    Component: 'Region',
    ComponentType: 'PointOfInterest',
    Id: '548c975c-40c2-434f-a498-ff9494d079e5',
    Indexable: true,
    Name: 'Region',
  },
  SuburbanArea: {
    Component: 'SuburbanArea',
    ComponentType: 'PointOfInterest',
    Id: '550089e9-a62c-40c6-acc6-66a8a9aff046',
    Indexable: true,
    Name: 'SuburbanArea',
  },
  ThemePark: {
    CanonicalSlugs: { en: 'theme-park', fr: 'parc-dattraction' },
    Component: 'ThemePark',
    ComponentType: 'PointOfInterest',
    Id: 'c94f1938-d274-44e0-8273-b949d1625388',
    Indexable: true,
    Name: 'ThemePark',
    Slugs: ['theme-park', 'parc-dattraction'],
  },
}
